#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
kotlin.incremental=true
kotlin.incremental.multiplatform=true
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.androidSourceSetLayoutV2AndroidStyleDirs.nowarn=true

#Gradle
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=false
android.newDsl=false